### ISSUE TITLE
Missing multiple values of dct:isRequiredBy

### ISSUE THREAD

**Issue by tfrancart** [flopezag/IoTAgent-Turtle#66]
In the "structures-tourism.ttl" input example file we have 2 values for dct:isRequiredBy :

```
<http://bauhaus/structuresDeDonnees/structure/dsd1001> dct:isRequiredBy "Melodi-Chargement" , "Melodi-Diffusion" .
```

However only one is in the JSON-LD output after conversion:

```
"dct:isRequiredBy": "Melodi-Chargement",
```

**Comment by flopezag** [comment]
It is related to the management of the flatten_value function inside the listmanagement.py the issue has been resolved.
